/**
 * A minimal pdf.js viewer built on the prebuilt components shipped in
 * pdfjs-dist (`web/pdf_viewer.mjs`). Copied into public/pdfjs/web/ by
 * scripts/copy-pdfjs.js.
 *
 * Design rules, in order of importance:
 *  1. No download / print / open-file affordance exists. The app's whole
 *     premise is "look, don't take", so the toolbar is simply absent.
 *  2. It will only ever open a URL on our own origin under /content/.
 *     `file=` is attacker-controllable in principle, so it is validated here
 *     as well as being generated by us.
 *  3. No `eval`: `isEvalSupported: false` keeps 'unsafe-eval' out of the CSP.
 *  4. Fits to page width and stays fitted when the phone rotates.
 */

const statusEl = document.getElementById('status');

function setStatus(message) {
  statusEl.textContent = message;
}

function fail(message, error) {
  setStatus(message);
  if (error) console.error(error);
}

/** Resolve an asset that sits next to (or above) this script. */
function asset(relative) {
  return new URL(relative, import.meta.url).href;
}

/** `#zoom=page-width` etc. Anything unrecognised falls back to page width. */
function zoomFromHash() {
  const value = new URLSearchParams(location.hash.replace(/^#/, '')).get('zoom');
  return ['page-width', 'page-fit', 'page-height', 'auto'].includes(value) ? value : 'page-width';
}

/**
 * The only documents this page will open are same-origin ones served by our
 * own proxy. A relative `file=` is fine; anything else is refused outright.
 */
function resolveFileParam() {
  const raw = new URLSearchParams(location.search).get('file');
  if (!raw) throw new Error('No file parameter.');

  let url;
  try {
    url = new URL(raw, location.href);
  } catch {
    throw new Error('Malformed file parameter.');
  }
  if (url.origin !== location.origin) {
    throw new Error('Refusing to open a document from another origin.');
  }
  if (!url.pathname.startsWith('/content/')) {
    throw new Error('Refusing to open a URL outside /content/.');
  }
  return url.href;
}

async function main() {
  const fileUrl = resolveFileParam();

  // Order matters: pdf_viewer.mjs reads globalThis.pdfjsLib at evaluation
  // time, which pdf.min.mjs is what sets. Dynamic imports make that explicit
  // rather than relying on static-import ordering.
  await import('../build/pdf.min.mjs');
  await import('./pdf_viewer.mjs');

  const pdfjsLib = globalThis.pdfjsLib;
  const { EventBus, PDFLinkService, PDFViewer } = globalThis.pdfjsViewer;

  pdfjsLib.GlobalWorkerOptions.workerSrc = asset('../build/pdf.worker.min.mjs');

  const container = document.getElementById('viewerContainer');
  const eventBus = new EventBus();
  const linkService = new PDFLinkService({
    eventBus,
    externalLinkTarget: 2, // LinkTarget.BLANK
    externalLinkRel: 'noopener noreferrer nofollow',
  });

  const pdfViewer = new PDFViewer({
    container,
    viewer: document.getElementById('viewer'),
    eventBus,
    linkService,
    textLayerMode: 1, // selectable text, no enhanced layer
    annotationMode: 1, // render annotations; no form widgets
    annotationEditorMode: -1, // editing disabled
  });
  linkService.setViewer(pdfViewer);

  eventBus.on('pagesinit', () => {
    pdfViewer.currentScaleValue = zoomFromHash();
    setStatus('');
  });

  // Data attributes are the handshake with the E2E suite: they let a test
  // assert that pages really rendered rather than that an iframe exists.
  eventBus.on('pagesloaded', (event) => {
    document.documentElement.dataset.pdfPages = String(event.pagesCount ?? pdfViewer.pagesCount);
  });
  eventBus.on('pagerendered', (event) => {
    document.documentElement.dataset.pdfRendered = String(event.pageNumber);
  });

  const loadingTask = pdfjsLib.getDocument({
    url: fileUrl,
    cMapUrl: asset('../cmaps/'),
    cMapPacked: true,
    standardFontDataUrl: asset('../standard_fonts/'),
    wasmUrl: asset('../wasm/'),
    iccUrl: asset('../iccs/'),
    // Read-only viewer: no PDF JavaScript, no XFA forms, no eval.
    isEvalSupported: false,
    enableScripting: false,
    enableXfa: false,
  });

  const pdfDocument = await loadingTask.promise;
  pdfViewer.setDocument(pdfDocument);
  linkService.setDocument(pdfDocument, null);

  let resizeTimer = null;
  window.addEventListener('resize', () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => {
      if (pdfViewer.pagesCount > 0) pdfViewer.currentScaleValue = zoomFromHash();
    }, 150);
  });

  wireImmersiveTapForwarding(container);
}

/**
 * Forward a tap to the parent's full-screen chrome toggle.
 *
 * A tap inside this iframe can never bubble to the parent document, so
 * public/viewer.js cannot see it directly -- this is the only way it learns
 * "she tapped the document". `key: Escape` exists for the same reason in the
 * other direction: once a tap has happened, focus lives in here, so the
 * parent's own Escape listener would never fire again without this.
 *
 * Exactly two message shapes, always to our own origin (never `'*'`), and
 * only when this page is actually embedded -- the same file also loads
 * top-level in view.spec.js's "refuses to open anything outside our proxy"
 * check, where `window.parent === window` and none of this should run.
 */
function wireImmersiveTapForwarding(container) {
  if (window.parent === window) return;

  const post = (message) => window.parent.postMessage({ v: 1, source: 'ostrich-pdf', ...message }, window.location.origin);

  const TAP_MOVE_PX = 10;
  const TAP_MAX_MS = 500;
  let start = null;

  container.addEventListener('pointerdown', (event) => {
    if (event.target.closest('a')) {
      start = null; // a link inside the document, not a tap on it
      return;
    }
    start = { x: event.clientX, y: event.clientY, t: Date.now(), scrollTop: container.scrollTop };
  });

  container.addEventListener('pointerup', (event) => {
    const from = start;
    start = null;
    if (!from) return;

    const dx = Math.abs(event.clientX - from.x);
    const dy = Math.abs(event.clientY - from.y);
    const dt = Date.now() - from.t;
    const scrolled = container.scrollTop !== from.scrollTop;
    if (dx > TAP_MOVE_PX || dy > TAP_MOVE_PX || dt > TAP_MAX_MS || scrolled) return;

    post({ type: 'tap' });
  });

  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') post({ type: 'key', key: 'Escape' });
  });
}

main().catch((error) => {
  fail("We couldn't show this document.", error);
  document.documentElement.dataset.pdfError = '1';
});
