import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Configuration loading. Fails fast and loudly: a half-configured deployment
 * should never boot and then mysteriously 500 on the first request.
 */

class ConfigError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ConfigError';
  }
}

const HEX_32_BYTES = /^[0-9a-fA-F]{64}$/;

function required(env, key, hint) {
  const value = env[key];
  if (value === undefined || String(value).trim() === '') {
    throw new ConfigError(
      `Missing required environment variable ${key}. ${hint}\n` +
        'See .env.example for the full list.'
    );
  }
  return String(value).trim();
}

/**
 * Strip a trailing slash so we can always join with `/...` safely.
 */
function normalizeBaseUrl(raw) {
  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new ConfigError(
      `NC_BASE_URL is not a valid URL: ${JSON.stringify(raw)}. ` +
        'Expected something like http://nextcloud.lan or https://cloud.example.com'
    );
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new ConfigError(`NC_BASE_URL must be http:// or https://, got ${url.protocol}`);
  }
  return url.toString().replace(/\/+$/, '');
}

/**
 * viewers.json: [{ name, label, passphraseHash }]
 * `name` identifies the person (used by M4's "new since you last looked").
 */
export function loadViewers(filePath) {
  let raw;
  try {
    raw = readFileSync(filePath, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') {
      throw new ConfigError(
        `Viewers file not found at ${filePath}.\n` +
          'Copy config/viewers.example.json to config/viewers.json and add a passphrase hash\n' +
          'generated by:  node scripts/hash-passphrase.js'
      );
    }
    throw new ConfigError(`Could not read viewers file ${filePath}: ${err.message}`);
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new ConfigError(`Viewers file ${filePath} is not valid JSON: ${err.message}`);
  }

  if (!Array.isArray(parsed) || parsed.length === 0) {
    throw new ConfigError(
      `Viewers file ${filePath} must be a non-empty JSON array of ` +
        '{ "name", "label", "passphraseHash" } objects.'
    );
  }

  return parsed.map((viewer, i) => {
    for (const key of ['name', 'passphraseHash']) {
      if (typeof viewer?.[key] !== 'string' || viewer[key].trim() === '') {
        throw new ConfigError(
          `Viewer #${i + 1} in ${filePath} is missing a non-empty "${key}" string.`
        );
      }
    }
    if (!viewer.passphraseHash.startsWith('$2')) {
      throw new ConfigError(
        `Viewer "${viewer.name}" in ${filePath} does not look like a bcrypt hash ` +
          '(expected it to start with "$2"). Generate one with scripts/hash-passphrase.js.'
      );
    }
    return {
      name: viewer.name.trim(),
      label: typeof viewer.label === 'string' && viewer.label.trim() ? viewer.label.trim() : viewer.name.trim(),
      passphraseHash: viewer.passphraseHash,
    };
  });
}

/**
 * @param {NodeJS.ProcessEnv} env
 * @returns {{
 *   nextcloud: { baseUrl: string, user: string, appPassword: string },
 *   sessionKey: Buffer,
 *   port: number,
 *   host: string,
 *   isProduction: boolean,
 *   viewersFile: string,
 *   viewers: Array<{name: string, label: string, passphraseHash: string}>,
 * }}
 */
export function loadConfig(env = process.env) {
  const baseUrl = normalizeBaseUrl(
    required(env, 'NC_BASE_URL', 'This is the LAN/docker address of Nextcloud, not the public URL.')
  );
  const user = required(env, 'NC_USER', 'The dedicated read-only viewer account, e.g. ostrich-viewer.');
  const appPassword = required(
    env,
    'NC_APP_PASSWORD',
    'An app password for NC_USER (Settings > Security > Devices & sessions).'
  );

  const sessionSecret = required(
    env,
    'SESSION_SECRET',
    'Generate with: node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"'
  );
  if (!HEX_32_BYTES.test(sessionSecret)) {
    throw new ConfigError(
      'SESSION_SECRET must be exactly 64 hex characters (32 bytes).\n' +
        'Generate with: node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"'
    );
  }

  const portRaw = env.PORT ?? '3000';
  const port = Number.parseInt(portRaw, 10);
  if (!Number.isInteger(port) || port < 0 || port > 65535) {
    throw new ConfigError(`PORT must be an integer between 0 and 65535, got ${JSON.stringify(portRaw)}`);
  }

  const viewersFile = resolve(env.VIEWERS_FILE ?? 'config/viewers.json');

  return {
    nextcloud: { baseUrl, user, appPassword },
    sessionKey: Buffer.from(sessionSecret, 'hex'),
    port,
    host: env.HOST ?? '0.0.0.0',
    isProduction: env.NODE_ENV === 'production',
    // Secure-by-default: only an explicit dev/test NODE_ENV downgrades the
    // session cookie. `npm start` with no NODE_ENV must behave as production.
    cookieSecure: env.NODE_ENV !== 'development' && env.NODE_ENV !== 'test',
    viewersFile,
    viewers: loadViewers(viewersFile),
  };
}

export { ConfigError };
